import { AppPage } from './app.po';

describe('workspace-project App', () => {
  let page: AppPage;

  beforeEach(() => {
    page = new AppPage();
  });

  it('should display main heading which is `Angular ngx-model example`', () => {
    page.navigateTo();
    expect(page.getMainText()).toEqual('Angular ngx-model example');
  });

  it('should display a paragraph text', () => {
    page.navigateTo();
    expect(page.getParagraphText()).toBe(
      `This is a minimal example of using ngx model in a Angular 6 project generated by the Angular CLI`
    );
  });

  it('should enter the name that name will display in the bottom of the input field', () => {
    page.navigateTo();
    page.getNameInput().clear();
    page.getNameInput().sendKeys('Saad');
    expect(page.getNameText()).toEqual('Hello, Saad!');
  });
});
